spring:
    sleuth:
        otel:
            exporter:
                otlp:
                    endpoint: <otlp-url>
                    enabled: true

pod:
    name: test-123

openshift:
    cluster: local

aurora:
    klientid: aup/test-app/1.2.3